# Site
name: 'Getfreelancy'
description: 'Work From Home'
logo: ''
favicon: ''
baseurl: '/'
disqus: ''
email: 'admin@getfreelancy.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           GetFreelancy
      site:           https://getfreelancy.com
      avatar:         
      bio:            
      email:          
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Freelancy
      avatar: 
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]